# Project Euler
# projecteuler.net
# Becca Kuss

# Libraries ---------------------------------------------------------------

library(dplyr)
library(tidyr)
library(stringr)


# Functions ---------------------------------------------------------------


# Sieve of Eratosthenes
sieve_of_eratosthenes <- function(n) {
  
  # Get all prime numbers up to n
  
  # let A be an array of Boolean values, indexed by integers 2 to n,
  # initially all set to true.
  a <- data.frame(ind = 2:n,
                  check = TRUE)
  
  # for i = 2, 3, 4, ..., not exceeding √n do
  for (i in 2:sqrt(n)) {
    
    # if A[i] is true
    progress <- a %>% filter(ind == i) %>% pull(check)
    if (progress) {
      
      # for j = i2, i2+i, i2+2i, i2+3i, ..., not exceeding n do
      j <- i^2
      x <- 1
      while (j < n) {
        
        # A[j] := false
        a$check[a$ind == j] <- FALSE
        j <- i^2 + (x * i)
        x <- x + 1
        
      }
    }
  }
  
  a %>%
    filter(check) %>%
    pull(ind)
  
}


# Problem 1 - Multiples of 3 and 5 ----------------------------------------

# If we list all the natural numbers below 10 that are multiples of 3 or 5, we
# get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.

data.frame(number = 1:999) %>%
  mutate(is_mult_3 = number %% 3 == 0,
         is_mult_5 = number %% 5 == 0) %>%
  filter(is_mult_3 | is_mult_5) %>%
  summarise(sum = sum(number)) %>%
  pull(sum)

# 233168

# Problem 2 - Even Fibonacci numbers --------------------------------------

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#  
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fn_minus1 <- 1
fn <- 1
fib_seq <- c()
while (fn < 4000000) {
  
  # Create the sequence
  fib_seq <- c(fib_seq, fn)
  
  # Increment to the next fn
  fn_plus1 <- fn + fn_minus1
  
  # Reset values
  fn_minus1 <- fn
  fn <- fn_plus1
  
}

data.frame(fn = fib_seq) %>%
  mutate(is_even = fn %% 2 == 0) %>%
  filter(is_even) %>%
  summarise(sum = sum(fn)) %>%
  pull(sum)

# 4613732

# Problem 3 - Largest prime factor ----------------------------------------

# The prime factors of 13195 are 5, 7, 13 and 29.
#
# What is the largest prime factor of the number 600851475143 ?

primes_up_to_n <- sieve_of_eratosthenes(30000)

# Check if our big number is divisible by each prime number
quotients <- 600851475143 / primes_up_to_n

integer_quotients <- 600851475143 %/% primes_up_to_n

max(primes_up_to_n[quotients == integer_quotients])

# 6857

# Problem 4 - Largest palindrome product ----------------------------------

# A palindromic number reads the same both ways. The largest palindrome made
# from the product of two 2-digit numbers is 9009 = 91 × 99.
#
# Find the largest palindrome made from the product of two 3-digit numbers.

three_digit_nums <- 100:999

three_digit_combos <- data.frame(num1 = three_digit_nums) %>%
  merge(data.frame(num2 = three_digit_nums)) %>%
  mutate(product = num1 * num2,
         product_char = as.character(product),
         n_char = str_length(product_char),
         first_digits = str_sub(product_char,
                                start = 1,
                                end = floor(n_char / 2)),
         first_digits_n_char = str_length(first_digits),
         digit_n = str_sub(product_char,
                           start = n_char,
                           end = n_char),
         digit_n_minus1 = str_sub(product_char,
                                  start = n_char - 1,
                                  end = n_char - 1),
         digit_n_minus2 = str_sub(product_char,
                                  start = n_char - 2,
                                  end = n_char - 2),
         last_digits_rev = if_else(first_digits_n_char == 2,
                                   paste0(digit_n, digit_n_minus1),
                                   paste0(digit_n, digit_n_minus1, digit_n_minus2)),
         is_palindrome = first_digits == last_digits_rev)

three_digit_combos %>%
  filter(is_palindrome) %>%
  summarise(max = max(product)) %>%
  pull(max)

# 906609

# Problem 5 - Smallest multiple -------------------------------------------

# 2520 is the smallest number that can be divided by each of the numbers from 1
# to 10 without any remainder.
#
# What is the smallest positive number that is evenly divisible by all of the
# numbers from 1 to 20?

divis_by_up_to <- 20

# Set starting values
number <- 0
found_it <- FALSE

while (!found_it & number < 2000000) {
  
  # Increment number
  number <- number + divis_by_up_to
  
  message(number)
  
  # Check if the number is divisible by each required number
  quotients <- number / (1:divis_by_up_to)
  
  integer_quotients <- number %/% (1:divis_by_up_to)
  
  found_it <- all(quotients == integer_quotients)
  
  
}

number


# Problem 6 - Sum square difference ---------------------------------------

# The sum of the squares of the first ten natural numbers is,
#
# The square of the sum of the first ten natural numbers is,
#
# Hence the difference between the sum of the squares of the first ten natural
# numbers and the square of the sum is .
#
# Find the difference between the sum of the squares of the first one hundred
# natural numbers and the square of the sum.


data.frame(number = 1:100) %>%
  mutate(square = number^2) %>%
  summarise(sum_of_squares = sum(square),
            square_of_sum = sum(number)^2) %>%
  mutate(difference = square_of_sum - sum_of_squares) %>%
  pull(difference)

# 25164150


# Problem 7 - 10001st prime -----------------------------------------------

# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see t
# hat the 6th prime is 13.
#
# What is the 10 001st prime number?


# Get all prime numbers up to 125k
first_primes <- sieve_of_eratosthenes(125000)

first_primes[10001]

# 104743


# Problem 8 - Largest product in a series ---------------------------------

# The four adjacent digits in the 1000-digit number that have the greatest
# product are 9 × 9 × 8 × 9 = 5832.
#
# 73167176531330624919225119674426574742355349194934
# 96983520312774506326239578318016984801869478851843
# 85861560789112949495459501737958331952853208805511
# 12540698747158523863050715693290963295227443043557
# 66896648950445244523161731856403098711121722383113
# 62229893423380308135336276614282806444486645238749
# 30358907296290491560440772390713810515859307960866
# 70172427121883998797908792274921901699720888093776
# 65727333001053367881220235421809751254540594752243
# 52584907711670556013604839586446706324415722155397
# 53697817977846174064955149290862569321978468622482
# 83972241375657056057490261407972968652414535100474
# 82166370484403199890008895243450658541227588666881
# 16427171479924442928230863465674813919123162824586
# 17866458359124566529476545682848912883142607690042
# 24219022671055626321111109370544217506941658960408
# 07198403850962455444362981230987879927244284909188
# 84580156166097919133875499200524063689912560717606
# 05886116467109405077541002256983155200055935729725
# 71636269561882670428252483600823257530420752963450
#
# Find the thirteen adjacent digits in the 1000-digit number that have the
# greatest product. What is the value of this product?


thsnd_digit_num <- paste0('73167176531330624919225119674426574742355349194934',
                          '96983520312774506326239578318016984801869478851843',
                          '85861560789112949495459501737958331952853208805511',
                          '12540698747158523863050715693290963295227443043557',
                          '66896648950445244523161731856403098711121722383113',
                          '62229893423380308135336276614282806444486645238749',
                          '30358907296290491560440772390713810515859307960866',
                          '70172427121883998797908792274921901699720888093776',
                          '65727333001053367881220235421809751254540594752243',
                          '52584907711670556013604839586446706324415722155397',
                          '53697817977846174064955149290862569321978468622482',
                          '83972241375657056057490261407972968652414535100474',
                          '82166370484403199890008895243450658541227588666881',
                          '16427171479924442928230863465674813919123162824586',
                          '17866458359124566529476545682848912883142607690042',
                          '24219022671055626321111109370544217506941658960408',
                          '07198403850962455444362981230987879927244284909188',
                          '84580156166097919133875499200524063689912560717606',
                          '05886116467109405077541002256983155200055935729725',
                          '71636269561882670428252483600823257530420752963450')

digits <- data.frame(digit = str_split(thsnd_digit_num, "")[[1]]) %>%
  mutate(digit = as.numeric(as.character(digit)))

adj_digits <- 13
for (col in 1:(adj_digits - 1)) {
  digits <- digits %>%
    mutate(UQ(paste0("lag", col)) := lag(digit, col))
}

digits %>%
  mutate(product = digit * lag1 * lag2 * lag3 * lag4 * lag5 * lag6 * lag7 *
           lag8 * lag9 * lag10 * lag11 * lag12) %>%
  filter(!is.na(product)) %>%
  pull(product) %>%
  max()

# 23514624000

# Problem 9 - Special Pythagorean triplet ---------------------------------

# A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
#
# a2 + b2 = c2
# For example, 32 + 42 = 9 + 16 = 25 = 52.
#
# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
# Find the product abc.

# Algebra:
# c = 1000 - (a + b)
# a^2 + b^2 = (1000 - (a + b))^2
# a^2 + b^2 = 1000^2 - 1000*(a+b) - 1000*(a+b) + (a+b)^2
# a^2 + b^2 = 1000^2 - 1000*(a+b) - 1000*(a+b) + a^2 + 2ab + b^2
# 0 = 1000^2 - 1000*(a+b) - 1000*(a+b) + 2ab
# 0 = 1000^2 - 2000a - 2000b + 2ab

# Brute force:
try_up_to <- 1000
data.frame(a = 1:try_up_to) %>%
  merge(data.frame(b = 1:try_up_to)) %>%
  filter(a < b) %>%
  mutate(a2 = a^2,
         b2 = b^2,
         c2 = a2 + b2,
         c = sqrt(c2),
         sum = a + b + c,
         product = a * b * c) %>%
  filter(sum == 1000) %>%
  pull(product)

# 31875000


# Problem 10 - Summation of primes ----------------------------------------

# The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
#
# Find the sum of all the primes below two million.


# Problem 11 - Largest product in a grid ----------------------------------

# In the 20×20 grid below, four numbers along a diagonal line have been marked
# in red.
#
# 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
# 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
# 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
# 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
# 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
# 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
# 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
# 67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
# 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
# 21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
# 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
# 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
# 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
# 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
# 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
# 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
# 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
# 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
# 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
# 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
#
# The product of these numbers is 26 × 63 × 78 × 14 = 1788696.
#
# What is the greatest product of four adjacent numbers in the same direction
# (up, down, left, right, or diagonally) in the 20×20 grid?

grid_raw <- data.frame(matrix(c(08, 02, 22, 97, 38, 15, 00, 40, 00, 75,
                                04, 05, 07, 78, 52, 12, 50, 77, 91, 08,
                                49, 49, 99, 40, 17, 81, 18, 57, 60, 87,
                                17, 40, 98, 43, 69, 48, 04, 56, 62, 00,
                                81, 49, 31, 73, 55, 79, 14, 29, 93, 71,
                                40, 67, 53, 88, 30, 03, 49, 13, 36, 65,
                                52, 70, 95, 23, 04, 60, 11, 42, 69, 24,
                                68, 56, 01, 32, 56, 71, 37, 02, 36, 91,
                                22, 31, 16, 71, 51, 67, 63, 89, 41, 92,
                                36, 54, 22, 40, 40, 28, 66, 33, 13, 80,
                                24, 47, 32, 60, 99, 03, 45, 02, 44, 75,
                                33, 53, 78, 36, 84, 20, 35, 17, 12, 50,
                                32, 98, 81, 28, 64, 23, 67, 10, 26, 38,
                                40, 67, 59, 54, 70, 66, 18, 38, 64, 70,
                                67, 26, 20, 68, 02, 62, 12, 20, 95, 63,
                                94, 39, 63, 08, 40, 91, 66, 49, 94, 21,
                                24, 55, 58, 05, 66, 73, 99, 26, 97, 17,
                                78, 78, 96, 83, 14, 88, 34, 89, 63, 72,
                                21, 36, 23, 09, 75, 00, 76, 44, 20, 45,
                                35, 14, 00, 61, 33, 97, 34, 31, 33, 95,
                                78, 17, 53, 28, 22, 75, 31, 67, 15, 94,
                                03, 80, 04, 62, 16, 14, 09, 53, 56, 92,
                                16, 39, 05, 42, 96, 35, 31, 47, 55, 58,
                                88, 24, 00, 17, 54, 24, 36, 29, 85, 57,
                                86, 56, 00, 48, 35, 71, 89, 07, 05, 44,
                                44, 37, 44, 60, 21, 58, 51, 54, 17, 58,
                                19, 80, 81, 68, 05, 94, 47, 69, 28, 73,
                                92, 13, 86, 52, 17, 77, 04, 89, 55, 40,
                                04, 52, 08, 83, 97, 35, 99, 16, 07, 97,
                                57, 32, 16, 26, 26, 79, 33, 27, 98, 66,
                                88, 36, 68, 87, 57, 62, 20, 72, 03, 46,
                                33, 67, 46, 55, 12, 32, 63, 93, 53, 69,
                                04, 42, 16, 73, 38, 25, 39, 11, 24, 94,
                                72, 18, 08, 46, 29, 32, 40, 62, 76, 36,
                                20, 69, 36, 41, 72, 30, 23, 88, 34, 62,
                                99, 69, 82, 67, 59, 85, 74, 04, 36, 16,
                                20, 73, 35, 29, 78, 31, 90, 01, 74, 31,
                                49, 71, 48, 86, 81, 16, 23, 57, 05, 54,
                                01, 70, 54, 71, 83, 51, 54, 69, 16, 92,
                                33, 48, 61, 43, 52, 01, 89, 19, 67, 48),
                              nrow = 20,
                              byrow = TRUE))

grid <- grid_raw %>%
  mutate(row = 1:20) %>%
  gather("col", "value", starts_with("X")) %>%
  mutate(col = as.numeric(str_remove(col, "X")),
         diag_down = row - col,
         diag_up = row + col)

grid %>%
  # Get vertical groups of four
  group_by(col) %>%
  arrange(row) %>%
  mutate(above1 = lag(value, 1),
         above2 = lag(value, 2),
         above3 = lag(value, 3)) %>%
  ungroup() %>%
  # Get horizontal groups of four
  group_by(row) %>%
  arrange(col) %>%
  mutate(left1 = lag(value, 1),
         left2 = lag(value, 2),
         left3 = lag(value, 3)) %>%
  ungroup() %>%
  # Get diagonal-down groups of four
  group_by(diag_down) %>%
  arrange(row) %>%
  mutate(aboveleft1 = lag(value, 1),
         aboveleft2 = lag(value, 2),
         aboveleft3 = lag(value, 3)) %>%
  ungroup() %>%
  # Get diagonal-up groups of four
  group_by(diag_up) %>%
  arrange(col) %>%
  mutate(belowleft1 = lag(value, 1),
         belowleft2 = lag(value, 2),
         belowleft3 = lag(value, 3)) %>%
  ungroup() %>%
  # Calculate products
  mutate(vertical_product = value * above1 * above2 * above3,
         horizontal_product = value * left1 * left2 * left3,
         diag_down_product = value * aboveleft1 * aboveleft2 * aboveleft3,
         diag_up_product = value * belowleft1 * belowleft2 * belowleft3) %>%
  select(row, col, vertical_product, horizontal_product, diag_down_product,
         diag_up_product) %>%
  gather("group", "product", vertical_product:diag_up_product) %>%
  filter(!is.na(product)) %>%
  pull(product) %>%
  max()

# 70600674